const DRUGS = [
  // Analgesics & Antipyretics
  "Paracetamol 500mg", "Paracetamol 650mg", "Paracetamol 1000mg",
  "Ibuprofen 200mg", "Ibuprofen 400mg", "Ibuprofen 600mg",
  "Aspirin 75mg", "Aspirin 150mg", "Aspirin 325mg",
  "Diclofenac 50mg", "Diclofenac 75mg", "Diclofenac 100mg",
  "Naproxen 250mg", "Naproxen 500mg",
  "Mefenamic Acid 250mg", "Mefenamic Acid 500mg",
  "Ketorolac 10mg", "Ketorolac 30mg",
  "Tramadol 50mg", "Tramadol 100mg",
  "Aceclofenac 100mg", "Aceclofenac + Paracetamol",
  "Nimesulide 100mg", "Etoricoxib 60mg", "Etoricoxib 90mg",

  // Antibiotics
  "Amoxicillin 250mg", "Amoxicillin 500mg",
  "Amoxicillin + Clavulanate 625mg", "Amoxicillin + Clavulanate 1000mg",
  "Azithromycin 250mg", "Azithromycin 500mg",
  "Ciprofloxacin 250mg", "Ciprofloxacin 500mg", "Ciprofloxacin 750mg",
  "Levofloxacin 250mg", "Levofloxacin 500mg", "Levofloxacin 750mg",
  "Doxycycline 100mg",
  "Metronidazole 200mg", "Metronidazole 400mg", "Metronidazole 500mg",
  "Cefixime 200mg", "Cefixime 400mg",
  "Cefpodoxime 100mg", "Cefpodoxime 200mg",
  "Cefalexin 250mg", "Cefalexin 500mg",
  "Cotrimoxazole 480mg", "Cotrimoxazole 960mg",
  "Clarithromycin 250mg", "Clarithromycin 500mg",
  "Erythromycin 250mg", "Erythromycin 500mg",
  "Tinidazole 300mg", "Tinidazole 500mg",
  "Ofloxacin 200mg", "Ofloxacin 400mg",
  "Norfloxacin 400mg",

  // Antihypertensives
  "Amlodipine 2.5mg", "Amlodipine 5mg", "Amlodipine 10mg",
  "Atenolol 25mg", "Atenolol 50mg", "Atenolol 100mg",
  "Metoprolol 25mg", "Metoprolol 50mg", "Metoprolol 100mg",
  "Losartan 25mg", "Losartan 50mg", "Losartan 100mg",
  "Telmisartan 20mg", "Telmisartan 40mg", "Telmisartan 80mg",
  "Enalapril 2.5mg", "Enalapril 5mg", "Enalapril 10mg",
  "Ramipril 1.25mg", "Ramipril 2.5mg", "Ramipril 5mg", "Ramipril 10mg",
  "Lisinopril 2.5mg", "Lisinopril 5mg", "Lisinopril 10mg",
  "Hydrochlorothiazide 12.5mg", "Hydrochlorothiazide 25mg",
  "Furosemide 20mg", "Furosemide 40mg",
  "Spironolactone 25mg", "Spironolactone 50mg",
  "Nifedipine 10mg", "Nifedipine 20mg",
  "Carvedilol 3.125mg", "Carvedilol 6.25mg", "Carvedilol 12.5mg",
  "Bisoprolol 2.5mg", "Bisoprolol 5mg", "Bisoprolol 10mg",
  "Nebivolol 5mg",

  // Diabetes
  "Metformin 500mg", "Metformin 850mg", "Metformin 1000mg",
  "Glibenclamide 2.5mg", "Glibenclamide 5mg",
  "Glimepiride 1mg", "Glimepiride 2mg", "Glimepiride 3mg", "Glimepiride 4mg",
  "Gliclazide 40mg", "Gliclazide 80mg",
  "Sitagliptin 25mg", "Sitagliptin 50mg", "Sitagliptin 100mg",
  "Vildagliptin 50mg",
  "Dapagliflozin 5mg", "Dapagliflozin 10mg",
  "Empagliflozin 10mg", "Empagliflozin 25mg",
  "Pioglitazone 15mg", "Pioglitazone 30mg",
  "Metformin + Glimepiride 500/1mg", "Metformin + Glimepiride 500/2mg",
  "Insulin Regular", "Insulin NPH", "Insulin Glargine",

  // Gastrointestinal
  "Omeprazole 10mg", "Omeprazole 20mg", "Omeprazole 40mg",
  "Pantoprazole 20mg", "Pantoprazole 40mg",
  "Rabeprazole 10mg", "Rabeprazole 20mg",
  "Esomeprazole 20mg", "Esomeprazole 40mg",
  "Ranitidine 150mg", "Ranitidine 300mg",
  "Domperidone 10mg",
  "Metoclopramide 10mg",
  "Ondansetron 4mg", "Ondansetron 8mg",
  "Loperamide 2mg",
  "Dicyclomine 10mg", "Dicyclomine 20mg",
  "Lactulose Syrup",
  "Bisacodyl 5mg", "Bisacodyl 10mg",
  "Sucralfate 500mg", "Sucralfate 1000mg",
  "Itopride 50mg",
  "Levosulpiride 25mg", "Levosulpiride 75mg",

  // Respiratory
  "Salbutamol 2mg", "Salbutamol 4mg",
  "Salbutamol Inhaler 100mcg",
  "Budesonide Inhaler 100mcg", "Budesonide Inhaler 200mcg",
  "Fluticasone Inhaler 125mcg", "Fluticasone Inhaler 250mcg",
  "Montelukast 4mg", "Montelukast 5mg", "Montelukast 10mg",
  "Cetirizine 5mg", "Cetirizine 10mg",
  "Loratadine 10mg",
  "Fexofenadine 120mg", "Fexofenadine 180mg",
  "Levocetirizine 2.5mg", "Levocetirizine 5mg",
  "Dextromethorphan 10mg", "Dextromethorphan 15mg",
  "Bromhexine 4mg", "Bromhexine 8mg",
  "Ambroxol 30mg", "Ambroxol 75mg",
  "Acetylcysteine 200mg", "Acetylcysteine 600mg",
  "Theophylline 100mg", "Theophylline 200mg",
  "Prednisolone 5mg", "Prednisolone 10mg", "Prednisolone 20mg",
  "Dexamethasone 0.5mg", "Dexamethasone 4mg",

  // Cardiovascular
  "Atorvastatin 5mg", "Atorvastatin 10mg", "Atorvastatin 20mg",
  "Atorvastatin 40mg", "Atorvastatin 80mg",
  "Rosuvastatin 5mg", "Rosuvastatin 10mg", "Rosuvastatin 20mg",
  "Simvastatin 10mg", "Simvastatin 20mg", "Simvastatin 40mg",
  "Clopidogrel 75mg",
  "Warfarin 1mg", "Warfarin 2mg", "Warfarin 5mg",
  "Digoxin 0.125mg", "Digoxin 0.25mg",
  "Isosorbide Mononitrate 10mg", "Isosorbide Mononitrate 20mg",
  "Nitroglycerine 0.5mg",
  "Ivabradine 5mg", "Ivabradine 7.5mg",

  // Thyroid
  "Levothyroxine 25mcg", "Levothyroxine 50mcg",
  "Levothyroxine 75mcg", "Levothyroxine 100mcg",
  "Carbimazole 5mg", "Carbimazole 10mg",
  "Propylthiouracil 50mg",

  // Vitamins & Supplements
  "Vitamin B12 500mcg", "Vitamin B12 1000mcg",
  "Vitamin D3 60000 IU", "Vitamin D3 1000 IU",
  "Calcium + Vitamin D3 500mg",
  "Folic Acid 1mg", "Folic Acid 5mg",
  "Iron + Folic Acid",
  "Zinc 10mg", "Zinc 20mg",
  "Multivitamin Tablet",
  "Vitamin C 500mg", "Vitamin C 1000mg",
  "B-Complex Tablet",
  "Ferrous Sulphate 200mg",

  // Neurological & Psychiatric
  "Alprazolam 0.25mg", "Alprazolam 0.5mg",
  "Clonazepam 0.25mg", "Clonazepam 0.5mg", "Clonazepam 1mg",
  "Diazepam 2mg", "Diazepam 5mg",
  "Amitriptyline 10mg", "Amitriptyline 25mg",
  "Sertraline 25mg", "Sertraline 50mg", "Sertraline 100mg",
  "Escitalopram 5mg", "Escitalopram 10mg", "Escitalopram 20mg",
  "Gabapentin 100mg", "Gabapentin 300mg", "Gabapentin 400mg",
  "Pregabalin 25mg", "Pregabalin 75mg", "Pregabalin 150mg",
  "Phenytoin 50mg", "Phenytoin 100mg",
  "Carbamazepine 100mg", "Carbamazepine 200mg",
  "Levetiracetam 250mg", "Levetiracetam 500mg",

  // Topical / Eye / Ear
  "Betamethasone Cream 0.1%",
  "Clotrimazole Cream 1%",
  "Mupirocin Ointment 2%",
  "Ciprofloxacin Eye Drops 0.3%",
  "Tobramycin Eye Drops 0.3%",
  "Ofloxacin Eye Drops 0.3%",
  "Sodium Cromoglycate Eye Drops",
  "Ciprofloxacin Ear Drops",
];

export default DRUGS;
